### ISSUE TITLE
Felt FullName ekstisterer blot for at ToString kan returnere det.

### ISSUE THREAD

**Issue by VirtualSatai** [SW2A305/Kildekode#86]

**Comment by AngelOD** [comment]
Jeg ser ikke dette som et problem. Vi har blot taget højde for, at andre dele af programmet ville kunne bruge det på et senere tidspunkt. Eksempelvis i forbindelse med nyhedsbreve.

Så jeg lukker det. Hvis nogen er uenig kan de bare åbne det igen.
